name: Update Packagist

on:
  push:
    tags:
      - '*'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@${{ github.ref }}
        
      - name: Packagist Update
        uses: mnavarrocarter/packagist-update@v1.0.0
        with:
          username: "terranc"
          api_token: ${{ secrets.packagist_token }}
